# Generated by Django 2.1.7 on 2019-03-24 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(default='01095673530', max_length=11)),
                ('major', models.CharField(default='영어영문', max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='profile')),
                ('lion', models.BooleanField(default=False)),
                ('grade', models.CharField(default='12', max_length=2)),
                ('purpose', models.TextField(default='지원동기')),
                ('service', models.TextField(default='만들고싶은서비스')),
                ('proj_exp', models.TextField(default='프로젝트 경험')),
                ('domain', models.TextField(default='관심분야')),
                ('portfolio', models.URLField(default='www.naver.com')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
