# Generated by Django 2.1.7 on 2019-03-25 07:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190324_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=markdownx.models.MarkdownxField(default="# Hi I'm lion", help_text='마크다운 형식으로 글을 작성하시오'),
        ),
    ]
